/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.customview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int font = 0x7f0300e2;
        public static final int fontProviderAuthority = 0x7f0300e4;
        public static final int fontProviderCerts = 0x7f0300e5;
        public static final int fontProviderFetchStrategy = 0x7f0300e6;
        public static final int fontProviderFetchTimeout = 0x7f0300e7;
        public static final int fontProviderPackage = 0x7f0300e8;
        public static final int fontProviderQuery = 0x7f0300e9;
        public static final int fontStyle = 0x7f0300ea;
        public static final int fontVariationSettings = 0x7f0300eb;
        public static final int fontWeight = 0x7f0300ec;
        public static final int ttcIndex = 0x7f030213;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050074;
        public static final int notification_icon_bg_color = 0x7f050075;
        public static final int ripple_material_light = 0x7f050082;
        public static final int secondary_text_default_material_light = 0x7f050084;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060057;
        public static final int compat_button_inset_vertical_material = 0x7f060058;
        public static final int compat_button_padding_horizontal_material = 0x7f060059;
        public static final int compat_button_padding_vertical_material = 0x7f06005a;
        public static final int compat_control_corner_material = 0x7f06005b;
        public static final int compat_notification_large_icon_max_height = 0x7f06005c;
        public static final int compat_notification_large_icon_max_width = 0x7f06005d;
        public static final int notification_action_icon_size = 0x7f0600db;
        public static 