/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.constraint;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int barrierAllowsGoneWidgets = 0x7f030037;
        public static final int barrierDirection = 0x7f030038;
        public static final int chainUseRtl = 0x7f03006c;
        public static final int constraintSet = 0x7f03009e;
        public static final int constraint_referenced_ids = 0x7f03009f;
        public static final int content = 0x7f0300a0;
        public static final int emptyVisibility = 0x7f0300c7;
        public static final int layout_constrainedHeight = 0x7f030122;
        public static final int layout_constrainedWidth = 0x7f030123;
        public static final int layout_constraintBaseline_creator = 0x7f030124;
        public static final int layout_constraintBaseline_toBaselineOf = 0x7f030125;
        public static final int layout_constraintBottom_creator = 0x7f030126;
        public static final int layout_constraintBottom_toBottomOf = 0x7f030127;
        public static final int layout_constraintBottom_toTopOf = 0x7f030128;
        public static final int layout_constraintCircle = 0x7f030129;
        public static final int layout_constraintCircleAngle = 0x7f03012a;
        public static final int layout_constraintCircleRadius = 0x7f03012b;
        public static final int layout_constraintDimensionRatio = 0x7f03012c;
        public static final int layout_constraintEnd_toEndOf = 0x7f03012d;
        public static final int layout_constraintEnd_toStartOf = 0x7f03012e;
        public static final int layout_constraintGuide_begin = 0x7f03012f;
        public static final int layout_constraintGuide_end = 0x7f030130;
        public static final int layout_constraintGuide_percent = 0x7f030131;
        public static final int layout_constraintHeight_default = 0x7f030132;
        public static final int layout_constraintHeight_max = 0x7f030133;
        public static final int layout_constraintHeight_min = 0x7f030134;
        public static final int layout_constraintHeight_percent = 0x7f030135;
        public static final int layout_constraintHorizontal_bias = 0x7f030136;
        public static final int layout_constraintHorizontal_chainStyle = 0x7f030137;
        public static final int layout_constraintHorizontal_weight = 0x7f030138;
        public static final int layout_constraintLeft_creator = 0x7f030139;
        public static final int layout_constraintLeft_toLeftOf = 0x7f03013a;
        public static final int layout_constraintLeft_toRightOf = 0x7f03013b;
        public static final int layout_constraintRight_creator = 0x7f03013c;
        public static final int layout_constraintRight_toLeftOf = 0x7f03013d;
        public static final int layout_constraintRight_toRightOf = 0x7f03013e;
        public static final int layout_constraintStart_toEndOf = 0x7f03013f;
        public static final int layout_constraintStart_toStartOf = 0x7f030140;
        public static final int layout_constraintTop_creator = 0x7f030141;
        public static final int layout_constraintTop_toBottomOf = 0x7f030142;
        public static final int layout_constraintTop_toTopOf = 0x7f030143;
        public static final int layout_constraintVertical_bias = 0x7f030144;
        public static final int layout_constraintVertical_chainStyle = 0x7f030145;
        public static final int layout_constraintVertical_weight = 0x7f030146;
        public static final int layout_constraintWidth_default = 0x7f030147;
        public static final int layout_constraintWidth_max = 0x7f030148;
        public static final int layout_constraintWidth_min = 0x7f030149;
        public static final int layout_constraintWidth_percent = 0x7f03014a;
        public static final int layout_editor_absoluteX = 0x7f03014c;
        public static final int layout_editor_absoluteY = 0x7f03014d;
        public static final int layout_goneMarginBottom = 0x7f03014e;
        public static final int layout_goneMarginEnd = 0x7f03014f;
        public static final int layout_goneMarginLeft = 0x7f030150;
        public static final int layout_goneMarginRight = 0x7f030151;
        public static final int layout_goneMarginStart = 0x7f030152;
        public static final int layout_goneMarginTop = 0x7f030153;
        public static final int layout_optimizationLevel = 0x7f030156;
    }
    public static final class id {
        private id() {}

        public static final int bottom = 0x7f080032;
        public static final int end = 0x7f080078;
        public static final int gone = 0x7f08009a;
        public static final int invisible = 0x7f0800ad;
        public static final int left = 0x7f0800b3;
        public static final int packed = 0x7f0800ff;
        public static final int parent = 0x7f080101;
        public static final int percent = 0x7f080104;
        public static final int right = 0x7f080120;
        public static final int spread = 0x7f080187;
        public static final int spread_inside = 0x7f080188;
        publi